name: Citron
id: citron

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: adam
  args:
    DEBIAN_FRONTEND: noninteractive

  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  # 🔧 Dev tools and headers
  - name: dev-packages
    type: shell
    commands:
      - apt-get install -y gcc make patch wget git dkms kmod linux-headers-6.12.38+deb13-amd64

  # 🎵 MacBook audio driver
  - name: macbook-audio-driver
    type: shell
    commands:
      - git clone https://github.com/davidjo/snd_hda_macbook.git /usr/src/snd_hda_macbook-0.1
      - cd /usr/src/snd_hda_macbook-0.1
      - |
        KVER=$(uname -r | cut -d. -f1,2)
        if dpkg --compare-versions "$KVER" ge "6.17"; then
          echo "Kernel >= 6.17 detected, running new installer"
          bash ./install.cirrus.driver.sh
        else
          echo "Kernel < 6.17 detected, running pre-6.17 installer"
          bash ./install.cirrus.driver.pre617.sh
        fi

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
      - apt-get autoremove -y
      - apt-get clean
      - lpkg --lock

  # Optional FsGuard (commented out)
  # - name: fsguard
  #   type: fsguard
  #   CustomFsGuard: false
  #   FsGuardLocation: "/usr/sbin/FsGuard"
  #   GenerateKey: true
  #   FilelistPaths: ["/usr/bin"]
  #   modules:
  #     - name: remove-prev-fsguard
  #       type: shell
  #       commands:
  #         - rm -rf /FsGuard
  #         - rm -f ./minisign.pub ./minisign.key
  #         - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
